# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 442f9ad32c33d694d4328a9002759fbc84384d7c674f0f34fb3b8587bab00f317ac048af1e095c7a786dd70391b0fd6e0b80b88c16fc44f1d4b13a8e4697472b

test:
  secret_key_base: 6b30db3dd632435d0f98b9e516c6c7fba381d571aa9bc39a0e03ac46abb9e89607bc3fea2bfdf3265ecb41bc873684fbcb1917a698a4172960c49e9b1f64a646

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
